# Generated by Django 5.1.4 on 2025-01-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_order_id_booking_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_response',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
