# Generated by Django 5.1.4 on 2025-01-08 15:36

import django.db.models.deletion
import django.utils.timezone
import apps.travelpackages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the country', max_length=100)),
                ('code', models.CharField(help_text='Three letter country code', max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the travel package', max_length=200)),
                ('city', models.CharField(help_text='City of the travel package', max_length=100)),
                ('image', models.ImageField(help_text='Image for the travel package', upload_to='packages/')),
                ('duration', models.IntegerField(help_text='Duration of the trip in days')),
                ('number_of_people', models.IntegerField(help_text='Recommended number of people')),
                ('highlights', models.TextField(blank=True, help_text="Key highlights of the package (e.g., 'River Cam / University Colleges')")),
                ('rating', models.FloatField(default=apps.travelpackages.models.get_random_rating, help_text='Average rating of the package')),
                ('reviews_count', models.PositiveIntegerField(default=apps.travelpackages.models.get_random_reviews, help_text='Number of reviews')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the package', max_digits=10)),
                ('available_start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('available_end_date', models.DateField(blank=True, default=apps.travelpackages.models.get_default_end_date, null=True)),
                ('booking_deadline', models.IntegerField(blank=True, default=7, help_text='Days before departure needed to book', null=True)),
                ('amenities', models.JSONField(blank=True, default=dict, help_text='List of amenities included', null=True)),
                ('itinerary', models.JSONField(blank=True, default=dict, help_text='Day-wise itinerary details', null=True)),
                ('transportation', models.TextField(blank=True, help_text='Transportation details', null=True)),
                ('accommodation', models.TextField(blank=True, help_text='Accommodation details', null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='moderate', max_length=20, null=True)),
                ('fitness_level', models.IntegerField(blank=True, default=1, help_text='Required fitness level (1-5)', null=True)),
                ('tour_language', models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='en', max_length=2, null=True)),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation policy details', null=True)),
                ('category', models.CharField(blank=True, choices=[('adventure', 'Adventure'), ('luxury', 'Luxury'), ('cultural', 'Cultural'), ('wildlife', 'Wildlife'), ('beach', 'Beach')], default='cultural', max_length=20, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_packages', to='travelpackages.country')),
            ],
            options={
                'verbose_name': 'Travel Package',
                'verbose_name_plural': 'Travel Packages',
            },
        ),
    ]
