# Generated by Django 5.1.4 on 2025-01-08 15:47

import django.utils.timezone
import apps.travelpackages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelpackages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='is_always_available',
            field=models.BooleanField(default=False, help_text='If true, package is available year-round regardless of dates'),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='available_end_date',
            field=models.DateField(blank=True, default=apps.travelpackages.models.get_default_end_date, help_text='Leave blank if package is always available', null=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='available_start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Leave blank if package is always available', null=True),
        ),
    ]
